// src/actions/actionTypes.js
export const UserActionTypes = {
    FETCH_USER_REQUEST: 'FETCH_USER_REQUEST',
    FETCH_USER_SUCCESS: 'FETCH_USER_SUCCESS',
    FETCH_USER_FAILURE: 'FETCH_USER_FAILURE',
    CREATE_USER_REQUEST: 'CREATE_USER_REQUEST',
    CREATE_USER_SUCCESS: 'CREATE_USER_SUCCESS',
    CREATE_USER_FAILURE: 'CREATE_USER_FAILURE',
    DELETE_USER_REQUEST: 'DELETE_USER_REQUEST',
    DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',
    DELETE_USER_FAILURE: 'DELETE_USER_FAILURE',
    UPDATE_USER_REQUEST: 'UPDATE_USER_REQUEST',
    UPDATE_USER_SUCCESS: 'UPDATE_USER_SUCCESS',
    UPDATE_USER_FAILURE: 'UPDATE_USER_FAILURE',
    ASSIGN_ROLE_REQUEST: 'ASSIGN_ROLE_REQUEST',
    ASSIGN_ROLE_SUCCESS: 'ASSIGN_ROLE_SUCCESS',
    ASSIGN_ROLE_FAILURE: 'ASSIGN_ROLE_FAILURE',
    FETCH_NEW_USERS_REQUEST: 'FETCH_NEW_USERS_REQUEST',
    FETCH_NEW_USERS_SUCCESS: 'FETCH_NEW_USERS_SUCCESS',
    FETCH_NEW_USERS_FAILURE: 'FETCH_NEW_USERS_FAILURE'
};

export const CourseActionTypes = {
    FETCH_COURSE_REQUEST: 'FETCH_COURSE_REQUEST',
    FETCH_COURSE_SUCCESS: 'FETCH_COURSE_SUCCESS',
    FETCH_COURSE_FAILURE: 'FETCH_COURSE_FAILURE',
    FETCH_COURSE_BY_ID_REQUEST: "FETCH_COURSE_BY_ID_REQUEST",
    FETCH_COURSE_BY_ID_SUCCESS: "FETCH_COURSE_BY_ID_SUCCESS",
    FETCH_COURSE_BY_ID_FAILURE: "FETCH_COURSE_BY_ID_FAILURE",
    CREATE_COURSE_REQUEST: 'CREATE_COURSE_REQUEST',
    CREATE_COURSE_SUCCESS: 'CREATE_COURSE_SUCCESS',
    CREATE_COURSE_FAILURE: 'CREATE_COURSE_FAILURE',
    DELETE_COURSE_REQUEST: 'DELETE_COURSE_REQUEST',
    DELETE_COURSE_SUCCESS: 'DELETE_COURSE_SUCCESS',
    DELETE_COURSE_FAILURE: 'DELETE_COURSE_FAILURE',
    UPDATE_COURSE_REQUEST: 'UPDATE_COURSE_REQUEST',
    UPDATE_COURSE_SUCCESS: 'UPDATE_COURSE_SUCCESS',
    UPDATE_COURSE_FAILURE: 'UPDATE_COURSE_FAILURE',
};
// categoryActionTypes.js
export const CategoryActionTypes = {
    FETCH_CATEGORY_REQUEST: 'FETCH_CATEGORY_REQUEST',
    FETCH_CATEGORY_SUCCESS: 'FETCH_CATEGORY_SUCCESS',
    FETCH_CATEGORY_FAILURE: 'FETCH_CATEGORY_FAILURE',
    FETCH_CATEGORY_BY_ID_REQUEST: 'FETCH_CATEGORY_BY_ID_REQUEST',
    FETCH_CATEGORY_BY_ID_SUCCESS: 'FETCH_CATEGORY_BY_ID_SUCCESS',
    FETCH_CATEGORY_BY_ID_FAILURE: 'FETCH_CATEGORY_BY_ID_FAILURE',
    CREATE_CATEGORY_REQUEST: 'CREATE_CATEGORY_REQUEST',
    CREATE_CATEGORY_SUCCESS: 'CREATE_CATEGORY_SUCCESS',
    CREATE_CATEGORY_FAILURE: 'CREATE_CATEGORY_FAILURE',
    DELETE_CATEGORY_REQUEST: 'DELETE_CATEGORY_REQUEST',
    DELETE_CATEGORY_SUCCESS: 'DELETE_CATEGORY_SUCCESS',
    DELETE_CATEGORY_FAILURE: 'DELETE_CATEGORY_FAILURE',
    UPDATE_CATEGORY_REQUEST: 'UPDATE_CATEGORY_REQUEST',
    UPDATE_CATEGORY_SUCCESS: 'UPDATE_CATEGORY_SUCCESS',
    UPDATE_CATEGORY_FAILURE: 'UPDATE_CATEGORY_FAILURE',
};
export const CourseSessionActionTypes = {
    FETCH_SESSIONS_REQUEST: 'FETCH_SESSIONS_REQUEST',
    FETCH_SESSIONS_SUCCESS: 'FETCH_SESSIONS_SUCCESS',
    FETCH_SESSIONS_FAILURE: 'FETCH_SESSIONS_FAILURE',
    CREATE_SESSION_REQUEST: 'CREATE_SESSION_REQUEST',
    CREATE_SESSION_SUCCESS: 'CREATE_SESSION_SUCCESS',
    CREATE_SESSION_FAILURE: 'CREATE_SESSION_FAILURE',
    UPDATE_SESSION_REQUEST: 'UPDATE_SESSION_REQUEST',
    UPDATE_SESSION_SUCCESS: 'UPDATE_SESSION_SUCCESS',
    UPDATE_SESSION_FAILURE: 'UPDATE_SESSION_FAILURE',
    DELETE_SESSION_REQUEST: 'DELETE_SESSION_REQUEST',
    DELETE_SESSION_SUCCESS: 'DELETE_SESSION_SUCCESS',
    DELETE_SESSION_FAILURE: 'DELETE_SESSION_FAILURE',
    FETCH_SESSIONS_BY_COURSE_ID_REQUEST: 'FETCH_SESSIONS_BY_COURSE_ID_REQUEST',
    FETCH_SESSIONS_BY_COURSE_ID_SUCCESS: 'FETCH_SESSIONS_BY_COURSE_ID_SUCCESS',
    FETCH_SESSIONS_BY_COURSE_ID_FAILURE: 'FETCH_SESSIONS_BY_COURSE_ID_FAILURE',
};
export const AuthActionTypes = {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    LOGOUT: 'LOGOUT',
    REGISTER_REQUEST: 'REGISTER_REQUEST',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAILURE: 'REGISTER_FAILURE',
    GET_USER_BY_TOKEN: 'GET_USER_BY_TOKEN',
};



